Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,19 +26,19 @@ commands:
         type: string
     steps:
       - run:
-        name: Revert migrations
-        when: on_fail
-        command: |
-          # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-          SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" \
-            --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
-          if(( $SUCCESS==1 )); 
-          then
-            cd ~/project/backend
-            npm install
-          #  Add revert code here. You can find this in the Getting Started section.
-            npm run migrations:revert
-          fi
+          name: Revert migrations
+          when: on_fail
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" \
+              --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              npm run migrations:revert
+            fi
             
 jobs:
   build-frontend:
@@ -47,16 +47,16 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [frontend-build]
+          keys: [frontend-build]
       - run:
-        name: Build front-end
-        command: |
-          cd frontend
-          npm install
-          npm run build
+          name: Build front-end
+          command: |
+            cd frontend
+            npm install
+            npm run build
       - save_cache:
-        paths: [frontend/node_modules]
-        key: frontend-build
+          paths: [frontend/node_modules]
+          key: frontend-build
 
   build-backend:
     docker:
@@ -64,17 +64,17 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [backend-build]
+          keys: [backend-build]
       - run:
-        name: Back-end build
-        command: |
-          cd backend
-          cat .env
-          npm install
-          npm run build
+          name: Back-end build
+          command: |
+            cd backend
+            cat .env
+            npm install
+            npm run build
       - save_cache:
-        paths: [backend/node_modules]
-        key: backend-build
+          paths: [backend/node_modules]
+          key: backend-build
 
   test-frontend:
     docker:
@@ -82,26 +82,26 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [frontend-build]
+          keys: [frontend-build]
       - run:
-        name: frontend tests
-        command: |
-          cd frontend
-          npm i
-          npm run test
-              
+          name: frontend tests
+          command: |
+            cd frontend
+            npm i
+            npm run test
+                
   test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-        keys: [backend-build]
+          keys: [backend-build]
       - run:
-        name: backend tests
-        command: |
-          cd backend
-          npm run test
+          name: backend tests
+          command: |
+            cd backend
+            npm run test
             
   scan-frontend:
     docker:
@@ -109,12 +109,12 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [frontend-build]
+          keys: [frontend-build]
       - run:
-        name: frontend scan
-        command: |
-          cd frontend
-          npm audit --audit-level=critical
+          name: frontend scan
+          command: |
+            cd frontend
+            npm audit --audit-level=critical
 
   scan-backend:
     docker:
@@ -122,12 +122,12 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [backend-build]
+          keys: [backend-build]
       - run:
-        name: backend scan
-        command: |
-          cd backend
-          npm audit --audit-level=critical
+          name: backend scan
+          command: |
+            cd backend
+            npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
@@ -135,37 +135,37 @@ jobs:
     steps:
       # Checkout code from git
       - run:
-        name: Ensure back-end infrastructure exists
-        command: |
-          aws cloudformation deploy \
-            --template-file .circleci/files/backend.yml \
-            #--tags project=your-tag \
-            # --stack-name "your back-end stack name with workflow id" \
-            # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
-            exit 1
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your back-end stack name with workflow id" \
+              # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
+              exit 1
       - run:
-        name: Ensure front-end infrastructure exist
-        command: |
-          aws cloudformation deploy \
-            --template-file .circleci/files/frontend.yml \
-            #--tags project=your-tag \
-            # --stack-name "your front-end stack name with workflow id" \
-            # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
-            exit 1
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              #--tags project=your-tag \
+              # --stack-name "your front-end stack name with workflow id" \
+              # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
+              exit 1
       - run:
-        name: Add back-end ip to ansible inventory
-        command: |
-          export BACKEND_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
-              --request GET https://api.memstash.io/values/backendurl)
-            echo "${BACKEND_URL}" >> .circleci/ansible/inventory.txt
-            cat .circleci/ansible/inventory.txt
+          name: Add back-end ip to ansible inventory
+          command: |
+            export BACKEND_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                --request GET https://api.memstash.io/values/backendurl)
+              echo "${BACKEND_URL}" >> .circleci/ansible/inventory.txt
+              cat .circleci/ansible/inventory.txt
       - persist_to_workspace:
-        root: ~/
-        paths:
-          - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure     
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+        # Here's where you will add some code to rollback on failure     
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}" 
+         workflow_id: "${CIRCLE_WORKFLOW_ID}" 
 
   configure-infrastructure:
     docker:
@@ -173,20 +173,20 @@ jobs:
     steps:
       - checkout
       - add_ssh_keys:
-        fingerprints:
-          - "	e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
+          fingerprints:
+            - "	e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
       - attach_workspace:
-        at: /tmp/.circleci/ansible
+          at: /tmp/.circleci/ansible
       - run:
-        name: Install dependencies
-        command: |
-          apk add --update ansible aws-cli
+          name: Install dependencies
+          command: |
+            apk add --update ansible aws-cli
       - run:
           name: Configure server
           command: |
             ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}"    
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"    
 
   run-migrations:
     docker:
@@ -194,12 +194,12 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [backend-build]
+          keys: [backend-build]
       - run:
-        name: Install dependencies
-        command: |
-          sudo apt update
-          sudo apt install -y awscli
+          name: Install dependencies
+          command: |
+            sudo apt update
+            sudo apt install -y awscli
       - run:
           name: Run migrations
           command: |
@@ -221,7 +221,7 @@ jobs:
       #     name: Send migration results to memstash
       #     command: |
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}"
+         workflow_id: "${CIRCLE_WORKFLOW_ID}"
      # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
@@ -230,30 +230,30 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-        keys: [frontend-build]
+          keys: [frontend-build]
       - run:
-        name: Install dependencies
-        command: |
-          yum install -y curl tar sudo
-            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
-            yum install -y nodejs
-            node --version
+          name: Install dependencies
+          command: |
+            yum install -y curl tar sudo
+              curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
+              yum install -y nodejs
+              node --version
       - run:
-        name: Get backend url
-        command: |
-          export API_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
-              --request GET https://api.memstash.io/values/backendurl)
-          export API_URL="http://${BACKEND_IP}:3030"
-          echo "${API_URL}" > .circleci/api_url.txt
+          name: Get backend url
+          command: |
+            export API_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                --request GET https://api.memstash.io/values/backendurl)
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "${API_URL}" > .circleci/api_url.txt
       - run:
-        name: Deploy frontend objects
-        command: |
-          export API_URL=$(cat .circleci/api_url.txt)
-            echo "${API_URL}" > frontend/.env
-            cd frontend
-            npm i
-            npm run build
-            aws s3 cp dist s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --recursive
+          name: Deploy frontend objects
+          command: |
+            export API_URL=$(cat .circleci/api_url.txt)
+              echo "${API_URL}" > frontend/.env
+              cd frontend
+              npm i
+              npm run build
+              aws s3 cp dist s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --recursive
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID}
       # Here's where you will add some code to rollback on failure      
@@ -264,26 +264,26 @@ jobs:
     steps:
       - checkout
       - add_ssh_keys:
-        fingerprints:
-          - "e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
+          fingerprints:
+            - "e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
       - restore_cache:
-        keys: [backend-build]
+         keys: [backend-build]
       - attach_workspace:
-        at: /tmp/artifacts
+          at: /tmp/artifacts
       - run:
-        name: Install dependencies
-        command: |
-          apk update
-          apk add --update ansible aws-cli openssh-client tar
+          name: Install dependencies
+          command: |
+            apk update
+            apk add --update ansible aws-cli openssh-client tar
       - run:
-        name: Deploy backend
-        command: |
-          tar -C /tmp/artifacts/backend -czvf artifact.tar.gz .
-          cd .circleci/ansible
-          export ANSIBLE_HOST_KEY_CHECKING=False
-          ansible-playbook -i /tmp/artifacts/inventory.txt deploy-backend.yml
+          name: Deploy backend
+          command: |
+            tar -C /tmp/artifacts/backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            export ANSIBLE_HOST_KEY_CHECKING=False
+            ansible-playbook -i /tmp/artifacts/inventory.txt deploy-backend.yml
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
   smoke-test:
@@ -292,30 +292,30 @@ jobs:
     steps:
       - checkout
       - run:
-        name: Install dependencies
-        command: |
-          sudo apt update
-          sudo apt install -y awscli
-          sudo apt install -y python3 ansible
+          name: Install dependencies
+          command: |
+            sudo apt update
+            sudo apt install -y awscli
+            sudo apt install -y python3 ansible
       - run:
-        name: Get backend url
-        command: |
-          curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
-              --request GET https://api.memstash.io/values/backendurl \
-              > backend-url.txt
+          name: Get backend url
+          command: |
+            curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                --request GET https://api.memstash.io/values/backendurl \
+                > backend-url.txt
       - run:
-        name: Backend smoke test.
-        command: |
-          url=$(cat backend-url.txt)
-            url="http://${url}:3030/api/status"
-            curl $url
+          name: Backend smoke test.
+          command: |
+            url=$(cat backend-url.txt)
+              url="http://${url}:3030/api/status"
+              curl $url
       - run:
-        name: Frontend smoke test.
-        command: |
-          URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com"
-            curl -s "${URL}"
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com"
+              curl -s "${URL}"
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
@@ -324,34 +324,34 @@ jobs:
     steps:
       - checkout
       - run:
-        name: Install dependencies
-        command: |
-          yum install -y curl
+          name: Install dependencies
+          command: |
+            yum install -y curl
       - run:
-        name: Install dependencies
-        command: |
-          yum install -y curl
+          name: Install dependencies
+          command: |
+            yum install -y curl
       - run:
-        name: Update cloudfront distribution
-        command: |
-          export OldWorkflowID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text)
-          export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-            --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-          echo "${OldWorkflowID}"
-          echo "${STACKS[@]}"
-          # save oldworkflowid for the cleanup phase
-          curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" \
-            --request PUT --data "${OldWorkflowID}" \
-              https://api.memstash.io/values/oldworkflowid
-          # promote
-          aws cloudformation update-stack \
-            --use-previous-template \
-            --stack-name cloudfront-${OldWorkflowID} \
-            --parameters ParameterKey=WorkflowID,ParameterValue=$CIRCLE_WORKFLOW_ID,UsePreviousValue=false
+          name: Update cloudfront distribution
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+                list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+                --no-paginate --output text)
+            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+            echo "${OldWorkflowID}"
+            echo "${STACKS[@]}"
+            # save oldworkflowid for the cleanup phase
+            curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" \
+              --request PUT --data "${OldWorkflowID}" \
+                https://api.memstash.io/values/oldworkflowid
+            # promote
+            aws cloudformation update-stack \
+              --use-previous-template \
+              --stack-name cloudfront-${OldWorkflowID} \
+              --parameters ParameterKey=WorkflowID,ParameterValue=$CIRCLE_WORKFLOW_ID,UsePreviousValue=false
       - destroy-environment:
-        workflow_id: "${CIRCLE_WORKFLOW_ID}"
+          workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
 cleanup:
