- update cicleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,32 +4,40 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      workflow_id:
+        type: string 
     steps:
       - run:
-          name: Destroy environments
-          when: on_fail
-          command: |
-            # Your code here
-            exit 1
+        name: Destroy environments
+        when: on_fail
+        command: |
+          if aws s3 ls | grep udapeople-<<parameters.workflow_id>>; then
+            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
+          fi
+          aws cloudformation delete-stack --stack-name frontend-<<parameters.workflow_id>>
+          aws cloudformation delete-stack --stack-name backend-<<parameters.workflow_id>>
+      - revert-migrations:
+        workflow_id: <<parameters.workflow_id>>
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      workflow_id:
+        type: string
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" \
+              --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
+             cd ~/project/backend
+             npm install
             #  Add revert code here. You can find this in the Getting Started section.
-              exit 1
+              npm run migrations:revert
             fi
             
 jobs:
@@ -39,15 +47,16 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+        keys: [frontend-build]
       - run:
-          name: Build front-end
-          command: |
-            # Your code here
-            exit 1
+        name: Build front-end
+        command: |
+          cd frontend
+          npm install
+          npm run build
       - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-build
+        paths: [frontend/node_modules]
+        key: frontend-build
 
   build-backend:
     docker:
@@ -55,212 +64,323 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+        keys: [backend-build]
       - run:
-          name: Back-end build
-          command: |
-             # Your code here
-             exit 1
+        name: Back-end build
+        command: |
+          cd backend
+          cat .env
+          npm install
+          npm run build
       - save_cache:
-          paths: [backend/node_modules]
-          key: backend-build
+        paths: [backend/node_modules]
+        key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-                
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
+      - run:
+        name: frontend tests
+        command: |
+          cd frontend
+          npm i
+          npm run test
+              
   test-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - run:
+        name: backend tests
+        command: |
+          cd backend
+          npm run test
             
   scan-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
+      - run:
+        name: frontend scan
+        command: |
+          cd frontend
+          npm audit --audit-level=critical
 
   scan-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - run:
+        name: backend scan
+        command: |
+          cd backend
+          npm audit --audit-level=critical
 
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
       # Checkout code from git
       - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-            # Your code here
+        name: Ensure back-end infrastructure exists
+        command: |
+          aws cloudformation deploy \
+            --template-file .circleci/files/backend.yml \
+            #--tags project=your-tag \
+            # --stack-name "your back-end stack name with workflow id" \
+            # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
             exit 1
+      - run:
+        name: Ensure front-end infrastructure exist
+        command: |
+          aws cloudformation deploy \
+            --template-file .circleci/files/frontend.yml \
+            #--tags project=your-tag \
+            # --stack-name "your front-end stack name with workflow id" \
+            # --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"  
+            exit 1
+      - run:
+        name: Add back-end ip to ansible inventory
+        command: |
+          export BACKEND_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+              --request GET https://api.memstash.io/values/backendurl)
+            echo "${BACKEND_URL}" >> .circleci/ansible/inventory.txt
+            cat .circleci/ansible/inventory.txt
       - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+        root: ~/
+        paths:
+          - project/.circleci/ansible/inventory.txt
+      # Here's where you will add some code to rollback on failure     
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}" 
 
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
+      - image: python:3.9.1-alpine3.12
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+        fingerprints:
+          - "	e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
+      - attach_workspace:
+        at: /tmp/.circleci/ansible
       - run:
-          name: Install dependencies
-          command: |
-            # Your code here
-            exit 1
+        name: Install dependencies
+        command: |
+          apk add --update ansible aws-cli
       - run:
           name: Configure server
           command: |
-            # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+            ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}"    
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      - checkout
+      - restore_cache:
+        keys: [backend-build]
+      - run:
+        name: Install dependencies
+        command: |
+          sudo apt update
+          sudo apt install -y awscli
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-            exit 1
+            cd backend
+            cat .env
+            npm i
+            npm run build
+            npm run migrations 2>&1 | tee migration-log.txt
+            status_code="${PIPESTATUS[0]}"
+            if [[ ! "${status_code}" == 0 ]]; then
+              return 1
+            fi
+            if cat migration-log.txt | grep "has been executed successfully"; then
+              curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                --request PUT --data "1" \
+                https://api.memstash.io/values/migration-"${CIRCLE_WORKFLOW_ID}"
+            fi
+      # - run:
+      #     name: Send migration results to memstash
+      #     command: |
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}"
      # Here's where you will add some code to rollback on failure      
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
+      - restore_cache:
+        keys: [frontend-build]
       - run:
-          name: Install dependencies
-          command: |
-            # your code here
+        name: Install dependencies
+        command: |
+          yum install -y curl tar sudo
+            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash -
+            yum install -y nodejs
+            node --version
       - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
+        name: Get backend url
+        command: |
+          export API_URL=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+              --request GET https://api.memstash.io/values/backendurl)
+          export API_URL="http://${BACKEND_IP}:3030"
+          echo "${API_URL}" > .circleci/api_url.txt
       - run:
-          name: Deploy frontend objects
-          command: |
-            # your code here
+        name: Deploy frontend objects
+        command: |
+          export API_URL=$(cat .circleci/api_url.txt)
+            echo "${API_URL}" > frontend/.env
+            cd frontend
+            npm i
+            npm run build
+            aws s3 cp dist s3://udapeople-"${CIRCLE_WORKFLOW_ID}" --recursive
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID}
       # Here's where you will add some code to rollback on failure      
                     
   deploy-backend:
     docker:
-      # Docker image here that supports Ansible
+      - image: python:3.9.1-alpine3.12
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+        fingerprints:
+          - "e9:55:aa:b4:5e:c0:07:6c:fb:e3:31:9f:c9:a3:c8:01"
+      - restore_cache:
+        keys: [backend-build]
+      - attach_workspace:
+        at: /tmp/artifacts
       - run:
-          name: Install dependencies
-          command: |
-            # your code here
+        name: Install dependencies
+        command: |
+          apk update
+          apk add --update ansible aws-cli openssh-client tar
       - run:
-          name: Deploy backend
-          command: |
-            # your code here
+        name: Deploy backend
+        command: |
+          tar -C /tmp/artifacts/backend -czvf artifact.tar.gz .
+          cd .circleci/ansible
+          export ANSIBLE_HOST_KEY_CHECKING=False
+          ansible-playbook -i /tmp/artifacts/inventory.txt deploy-backend.yml
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      - checkout
       - run:
-          name: Install dependencies
-          command: |
-            # your code here
+        name: Install dependencies
+        command: |
+          sudo apt update
+          sudo apt install -y awscli
+          sudo apt install -y python3 ansible
       - run:
-          name: Get backend url
-          command: |
-            # your code here
+        name: Get backend url
+        command: |
+          curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+              --request GET https://api.memstash.io/values/backendurl \
+              > backend-url.txt
       - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
+        name: Backend smoke test.
+        command: |
+          url=$(cat backend-url.txt)
+            url="http://${url}:3030/api/status"
+            curl $url
       - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
+        name: Frontend smoke test.
+        command: |
+          URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-us-east-1.amazonaws.com"
+            curl -s "${URL}"
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
   cloudfront-update:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
-          name: Install dependencies
-          command: |
-            # your code here
+        name: Install dependencies
+        command: |
+          yum install -y curl
       - run:
-          name: Update cloudfront distribution
-          command: |
-            # your code here
+        name: Install dependencies
+        command: |
+          yum install -y curl
+      - run:
+        name: Update cloudfront distribution
+        command: |
+          export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+          export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+            --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+          echo "${OldWorkflowID}"
+          echo "${STACKS[@]}"
+          # save oldworkflowid for the cleanup phase
+          curl -H "Content-Type: text/plain" -H "token: ${CIRCLE_WORKFLOW_ID}" \
+            --request PUT --data "${OldWorkflowID}" \
+              https://api.memstash.io/values/oldworkflowid
+          # promote
+          aws cloudformation update-stack \
+            --use-previous-template \
+            --stack-name cloudfront-${OldWorkflowID} \
+            --parameters ParameterKey=WorkflowID,ParameterValue=$CIRCLE_WORKFLOW_ID,UsePreviousValue=false
+      - destroy-environment:
+        workflow_id: "${CIRCLE_WORKFLOW_ID}"
       # Here's where you will add some code to rollback on failure  
 
 cleanup:
     docker:
-      # Docker image here
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
-          name: Get old stack workflow id
-          command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
+        name: Get old stack workflow id
+        command: |
+          # your code here
+          export OldWorkflowID="the id here"
+          export STACKS=[] #put the list of stacks here
       - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              # your code here
-            fi
+        name: Remove old stacks and files
+        command: |
+          export OldWorkflowID=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" \
+            --request GET https://api.memstash.io/values/oldworkflowid)
+          if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+          then
+            aws s3 rm s3://udapeople-"${OldWorkflowID}" --recursive
+            aws cloudformation delete-stack --stack-name frontend-"${OldWorkflowID}"
+            aws cloudformation delete-stack --stack-name backend-"${OldWorkflowID}"
+            aws cloudformation delete-stack --stack-name cloudfront-"${OldWorkflowID}"
+          fi
+          # if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+          # then
+          #   # your code here
+          # fi
             
 
 workflows:
